server:
  port: 7006
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:AmberBar/spring-cloud-study.git  # 配置git仓库的地址
          search-paths: GreenwichSR1/config-repository       # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                           # git仓库的账号
          password:

eureka:
  client:
    service-url:
      defaultZone: http://peer:8001/eureka