server:
  port: 9001
spring:
  application:
    name: microservice-provide-user
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-study
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
#      hibernate:
#        ddl-auto: update
#      show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
